version: '3.3'

services: 
  web:
    build: 
      context: ./app
    command: python cron.py
    volumes:
      - media_volume:/home/app/web/mediafiles
  nginx:
    build: 
      context: ./nginx
    volumes: 
      - media_volume:/home/app/web/mediafiles
    ports: 
      - 8001:8001
    # 昨晚忘记打开上传用端口了
    
volumes:
  media_volume: